Make it build on Macos and fix how you template a container template
poolsideai/sentencepiece pull request #23
Opened 2024-11-21 11:00 UTC by SokolAndrey

2024-11-21 19:43 UTC, vmarkovtsev requested changes

2024-11-21 19:43 UTC, vmarkovtsev commented on src/spm_bpe_cache_merge.cc
>      malloc_stats();
`malloc_stats()` doesn't depend on TCMALLOC and requires `malloc.h`: https://man7.org/linux/man-pages/man3/malloc_stats.3.html

We shouldn't replace `malloc.h` with `stdlib.h`. Instead, all the parts of the code that depend on `malloc.h` must be skipped on macOS:
```
#ifdef __GLIBC__
#include <malloc.h>
#endif

#ifdef __GLIBC__
malloc_stats();
#endif
```

2024-11-21 19:43 UTC, vmarkovtsev commented on src/bpe_model_trainer.cc
> +#include <stdlib.h>
Same here

2024-11-21 19:43 UTC, vmarkovtsev commented on src/trainer_interface.cc
> +#include <stdlib.h>
Same here

2024-11-21 19:43 UTC, vmarkovtsev commented on src/util.h
> +template <typename T, template <typename...> class C>
We must check that this doesn't break gcc on Linux, in return.

2024-11-22 11:36 UTC, SokolAndrey commented on src/util.h
> +template <typename T, template <typename...> class C>
could you pls give me some direction how we should test it besides building on a linux machine?

2024-11-29 17:26 UTC, vmarkovtsev commented on src/util.h
> +template <typename T, template <typename...> class C>
Just building is enough. Once it compiles, it should work!

2024-11-29 17:28 UTC, vmarkovtsev approved these changes
LGTM

2024-11-30 00:55 UTC, merged